name: arch_tools
description: A sample command-line application.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=3.0.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  alan:
    git:
      url: https://github.com/reyth3/alan.dart
      ref: fix/grpc
  grpc: ^3.2.4
  protobuf: ^2.1.0
  shared_preferences: ^2.2.3
  argon2: ^1.0.1
  pointycastle: ^3.9.1
  byte_extensions: ^0.0.3
  flutter_keychain: ^2.4.0
  fixnum: ^1.1.0
dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
